apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: busybox
            image: ikulyk404/busyboxplus:curl
            imagePullPolicy: Always
            command: ["sh", "-c", "curl http://todoapp-service/api/health"]
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "250m"
                memory: "128Mi"
